@set PATCH_VERSION_MAJOR=0
@set PATCH_VERSION_MINOR=94
@set PATCH_VERSION_DEFINES=/DPATCH_VERSION_MAJOR=%PATCH_VERSION_MAJOR% /DPATCH_VERSION_MINOR=%PATCH_VERSION_MINOR%
@rc /DPATCHVER=%PATCH_VERSION_MAJOR%,%PATCH_VERSION_MINOR%,0,0 resource.rc
@cl %* /c /Fa %PATCH_VERSION_DEFINES% /LD *.cpp
@link /DLL /DEF:d3d8.def /OUT:d3d8.dll /MAP *.obj resource.res user32.lib version.lib ole32.lib strmiids.lib